github: [AshishTalpada]
# Uncomment and configure additional funding platforms as needed:
# buy_me_a_coffee: ashish_talpada
# ko_fi: ashish_talpada
# patreon: ashish_talpada
# custom: ["https://www.paypal.me/AshishTalpada"]
