import json
import logging
import time
from typing import Any, Dict

logger = logging.getLogger(__name__)

class TradeThesisGenerator:
    """
    Generates a dense, multi-page Markdown audit thesis for every executed trade.
    Includes data from all voting agents, risk metrics, and macro context,
    providing complete explainability for compliance and post-mortem review.
    """
    def __init__(self, output_dir: str = "reports/thesis"):
        import os
        self.output_dir = output_dir
        os.makedirs(self.output_dir, exist_ok=True)

    def generate_markdown(self, trade_data: Dict[str, Any]) -> str:
        symbol = trade_data.get("symbol", "UNKNOWN")
        side = trade_data.get("side", "BUY")
        confidence = trade_data.get("confidence", 0.0)
        timestamp = time.strftime("%Y-%m-%d %H:%M:%S UTC", time.gmtime())

        votes = trade_data.get("votes", {})
        macro = trade_data.get("macro_context", {})

        md = f"# SOVEREIGN TRADE THESIS: {side} {symbol}\n\n"
        md += f"**Timestamp:** {timestamp}\n"
        md += f"**System Conviction:** {confidence:.2%}\n\n"

        md += "## Macro Context\n"
        for k, v in macro.items():
            md += f"- **{k.upper()}:** {v}\n"

        md += "\n## Agent Quorum Breakdown\n"
        for agent, vote in votes.items():
            md += f"- **{agent}:** {vote}\n"

        md += "\n## Risk Analysis\n"
        md += f"Expected Shortfall: {trade_data.get('expected_shortfall', 'N/A')}\n"
        md += f"Slippage Estimate: {trade_data.get('slippage_bps', 0.0)} bps\n"

        md += "\n---\n*Auto-generated by Sovereign Architect*"
        return md

    def save_thesis(self, trade_data: Dict[str, Any]) -> str:
        md = self.generate_markdown(trade_data)
        symbol = trade_data.get('symbol', 'UNK')
        filename = f"{self.output_dir}/thesis_{symbol}_{int(time.time())}.md"
        with open(filename, "w") as f:
            f.write(md)
        logger.info(f"[THESIS] Saved comprehensive thesis to {filename}")
        return filename
